DROP DATABASE IF EXISTS PART05_GENERATOR;
DROP DATABASE IF EXISTS PART05_MAPPING;
DROP DATABASE IF EXISTS PART05_SUBSELECT;
CREATE DATABASE PART05_GENERATOR;
CREATE DATABASE PART05_MAPPING;
CREATE DATABASE PART05_SUBSELECT;