DROP DATABASE IF EXISTS PART10_MANAGING_DATA;
CREATE DATABASE PART10_MANAGING_DATA;

DROP DATABASE IF EXISTS PART10_MANAGING_DATA_REPLICATE;
CREATE DATABASE PART10_MANAGING_DATA_REPLICATE;

DROP DATABASE IF EXISTS PART10_MANAGING_DATA2;
CREATE DATABASE PART10_MANAGING_DATA2;

