DROP DATABASE IF EXISTS PART12_FETCHING;
CREATE DATABASE PART12_FETCHING;

DROP DATABASE IF EXISTS PART12_FETCHING2;
CREATE DATABASE PART12_FETCHING2;

DROP DATABASE IF EXISTS PART12_FETCHING3;
CREATE DATABASE PART12_FETCHING3;

DROP DATABASE IF EXISTS PART12_FETCHING4;
CREATE DATABASE PART12_FETCHING4;

DROP DATABASE IF EXISTS PART12_FETCHING5;
CREATE DATABASE PART12_FETCHING5;

DROP DATABASE IF EXISTS PART12_FETCHING6;
CREATE DATABASE PART12_FETCHING6;

DROP DATABASE IF EXISTS PART12_FETCHING7;
CREATE DATABASE PART12_FETCHING7;

DROP DATABASE IF EXISTS PART12_FETCHING8;
CREATE DATABASE PART12_FETCHING8;

DROP DATABASE IF EXISTS PART12_FETCHING8_1;
CREATE DATABASE PART12_FETCHING8_1;

DROP DATABASE IF EXISTS PART12_FETCHING8_2;
CREATE DATABASE PART12_FETCHING8_2;

DROP DATABASE IF EXISTS PART12_FETCHING9;
CREATE DATABASE PART12_FETCHING9;

DROP DATABASE IF EXISTS PART12_FETCHING10;
CREATE DATABASE PART12_FETCHING10;